### ISSUE TITLE
Large stderr logfile size due to excessive logging

### ISSUE THREAD

**Issue by reethikar** [brave/zerotrace#3]
I currently log all the TCP errors we get when we ping different IPs. This was done to get an idea of what errors are returned when the ports is filtered or closed. [This line ](https://github.com/brave-experiments/proxy-detection-server/blob/9482741ef91a216bd0d6d0d6608260341a6e301c/cmd/test-server/main.go#L176) leads to logging these errors in a particular format in the `ErrLogger` file. 

The file is getting larger as most (now x/24=256 IPs) are getting pinged and have filtered ports. We should analyze the existing log files and then, reduce the amount of logging to ErrLogger done.

**Comment by NullHypothesis** [comment]
Closing this because we no longer use the `ErrLogger`.
