### ISSUE TITLE
Accessing webpage on mobile data causes error

### ISSUE THREAD

**Issue by reethikar** [brave/zerotrace#4]
Accessing the webpage on mobile data returns an unhelpful error on the webpage,`json: unsupported value: NaN` and console log says `Failed to load resource: the server responded with a status of 500 ()`

It fails to log anything useful on ErrLogger as well. It possibly fails when logging* all ICMP and TCP ping measurements and hence has an empty JSON, but this needs investigation to return better values that don't break UI.

**Comment by NullHypothesis** [comment]
The float64 type can be "not a number", which is probably what's happening here. We should be able to check for that with `math.IsNaN(value)`. My guess is that this happens when we calculate the mean.
